### ISSUE TITLE
Bad formatting for the blog post of VaryVary

### ISSUE THREAD

**Issue by Jnsll** [diverse-team/diverse-team.github.io#15]
There's a bad formatting for the blog post [http://www.diverse-team.fr/post/20190312-varyvary/](url). 
The link given is not routing to the page of the post.

**Comment by FAMILIAR-project** [comment]
Thanks a lot! 
It seems to be related to the feed.xml of VaryVary

Normally it should work now thanks to URL fix (my bad): 
https://github.com/VaryVary/varyvary.github.io/commit/bbfe2ca2c0b3c45f328c0c0c1d7c7d36e52e9e45
https://varyvary.github.io/feed.xml

I've added a comment to abuse the CI and rebuild the website ;-) 
https://github.com/diverse-team/diverse-team.github.io/blob/gh-pages-edit/tooling/atom2md/app.js
