### ISSUE TITLE
Word cloud

### ISSUE THREAD

**Issue by FAMILIAR-project** [diverse-team/diverse-team.github.io#18]
Hi, 

It is stated that: "Word cloud generated from abstract articles available on hal" 
but I found the word cloud not fully representative of what we're doing. 
I might be wrong but I suspect the word cloud is not up to date. 

I've tried to modify something here:
https://github.com/diverse-team/diverse-team.github.io/blob/gh-pages-edit/tooling/wordcloudgenerator/app.js#L56

maybe it's a static tool 

PS: not much time to investigate this issue

**Comment by oscarlvp** [comment]
Word cloud uses the terms from the keywords in the papers. We are not fetching the abstracts from HAL.
