### ISSUE TITLE
Fixing team vs. thesis + including "Alumni"

### ISSUE THREAD

**Issue by combemale** [diverse-team/diverse-team.github.io#20]
Currently, the section "Thesis" lists all Ph.D. students, including the current ones. These ones overlap with the section "Team" which also includes the (current) Ph.D. students. 

I would propose a section Team on the home page, with a link at the end to another page which list the "Alumni". Then we remove the thesis section. 

WDYT?

**Comment by Jnsll** [comment]
I agree with the separate Alumni page.

**Comment by oscarlvp** [comment]
Now we have two sections: current and former members.
