### ISSUE TITLE
Positions

### ISSUE THREAD

**Issue by FAMILIAR-project** [diverse-team/diverse-team.github.io#35]
Hi, 

A specific issue...
I had an announcement for a postdoc position https://www.diverse-team.fr/positions/slimfast/ but the URL is no longer valid since we have
https://www.diverse-team.fr/positions/
(previously it was https://www.diverse-team.fr/position/) 

Another stranged thing: https://www.diverse-team.fr/positions/slimfast/ works
but https://diverse-team.fr/positions/slimfast/ no :(

**Comment by oscarlvp** [comment]
Yes, it is `positions` now. 
No `diverse-team.fr` will not work. Should it work alongside the other?
I'm not sure how to do it.

**Comment by FAMILIAR-project** [comment]
Not sure either... it's not a critical problem, no problem
