### ISSUE TITLE
Blog posts: sort by date

### ISSUE THREAD

**Issue by FAMILIAR-project** [diverse-team/diverse-team.github.io#36]
Right now, it is based on the order of blogs referenced. 
Better to have last blog posts. 

I'm not familiar with Hugo, but it seems possible
https://gohugo.io/templates/lists#reverse-order

the template seems empty?
https://github.com/diverse-team/diverse-team.github.io/blob/gh-pages-edit/content/posts/_index.md 
it seems the data is well loaded:
https://github.com/diverse-team/diverse-team.github.io/blob/gh-pages-edit/tools/fetchposts.js

**Comment by oscarlvp** [comment]
Actual template is here https://github.com/diverse-team/diverse-team.github.io/blob/gh-pages-edit/layouts/posts/list.html
Fixed with 96e7127
