### ISSUE TITLE
Installation : youtube videos update, issue with Youtube API Key

### ISSUE THREAD

**Issue by Jnsll** [diverse-team/diverse-team.github.io#37]
In repo `diverse-team.github.io/tools`, command `npm run update`:

\> diverse-website-tools@1.0.0 update /DATA/These/Projects/diverse-team.github.io/tools
\> node main.js

Updating bibliography items
Obtaining the list of publications from HAL
Saving publications to ../data/publications.json
Generating word clouds
Done

Updating blog posts
Fetching posts from 5 sources
- Fetching posts from https://mleduc.xyz/feed.xml
- Fetching posts from http://olivier.barais.fr/feed.xml
- Fetching posts from https://torgen-engineering.blogspot.com/feeds/posts/default
- Fetching posts from http://blog.mathieuacher.com/feed.xml
- Fetching posts from https://varyvary.github.io/feed.xml
Saving posts to ../data/posts.json
Done

Updating profile images
Finding missing profile images
Profiles without image: 9
Retrieving image for emmanuel-chebbi
[WARNING] No Github id for gwendal-jouneaux. Site will use default image.
Retrieving image for hugo-martin
[WARNING] No Github id for janice-conquet. Site will use default image.
Retrieving image for luc-lesoil
[WARNING] No Github id for nelly-bencomo. Site will use default image.
Retrieving image for oscar-vera-perez
Retrieving image for quentin-le-dilavrec
[WARNING] No Github id for sophie-maupile. Site will use default image.
Done

Updating YouTube videos
Fetching list of videos from YouTube
[ERROR] Error: The request is missing a valid API key.

**Comment by oscarlvp** [comment]
There is an API key to retrieve the videos from the website, but, as the [README.md](https://github.com/diverse-team/diverse-team.github.io/blob/gh-pages-edit/README.md) says: 

> In this step the retrieval of the YouTube video list may fail if you do not use the API key for authentication. This is not essential and you can continue editing the website.
