### ISSUE TITLE
Diverse Coffee talks are not up to date

### ISSUE THREAD

**Issue by bloa** [diverse-team/diverse-team.github.io#63]
@garandria @gwendal-jouneaux ?

**Comment by garandria** [comment]
Good start [2e722b2](https://github.com/diverse-team/diverse-team.github.io/commit/2e722b2802ec824cc8a70a2796b7c8ac6632146c)

**Comment by garandria** [comment]
They are now.

**Comment by garandria** [comment]
@phoudail  @Steroux ?

**Comment by Steroux** [comment]
Done
